### ISSUE TITLE
复现您代码时出现问题

### ISSUE THREAD

**Issue by XiaPengcheng-PS** [Glooow1024/paper_collector#1]
大佬您好，目前我通过git clone大佬您的代码，然后也想爬取ieee的论文，但遇到的问题是，能打开那个页面，也能出现UI页面，但在输入要保存到的csv位置并开始后，能实时记录log信息，但是我在最终出现BYE BYE字样后，在保存的csv文件中不存在任何的信息，不知道是哪里出现了问题。

**Comment by Glooow1024** [comment]
是因为我之前提交的时候忘记把调试部分的代码删去了，所以实际上并没有开始爬论文。现在改过来了，你可以再试一下
